from enum import Enum


class EventType(Enum):
    # Book events
    BOOK_CREATED = "BOOK_CREATED"
    BOOK_PROCESSING_STARTED = "BOOK_PROCESSING_STARTED"
    BOOK_COMPLETED = "BOOK_COMPLETED"
    BOOK_COMPLETED_WITH_ERRORS = "BOOK_COMPLETED_WITH_ERRORS"

    # Page events
    PAGE_CREATED = "PAGE_CREATED"
    PAGE_PROCESSING_STARTED = "PAGE_PROCESSING_STARTED"
    PAGE_COMPLETED = "PAGE_COMPLETED"
    PAGE_FAILED = "PAGE_FAILED"

    # Chunk events
    CHUNK_CREATED = "CHUNK_CREATED"
    CHUNK_COMPLETED = "CHUNK_COMPLETED"
    CHUNK_FAILED = "CHUNK_FAILED"

    # Job events
    JOB_CREATED = "JOB_CREATED"
    JOB_QUEUED = "JOB_QUEUED"
    JOB_ASSIGNED = "JOB_ASSIGNED"
    JOB_STARTED = "JOB_STARTED"
    JOB_COMPLETED = "JOB_COMPLETED"
    JOB_FAILED = "JOB_FAILED"
    JOB_RETRY = "JOB_RETRY"

    # Worker events
    WORKER_REGISTERED = "WORKER_REGISTERED"
    WORKER_ONLINE = "WORKER_ONLINE"
    WORKER_OFFLINE = "WORKER_OFFLINE"
    WORKER_UNHEALTHY = "WORKER_UNHEALTHY"
    WORKER_RECOVERED = "WORKER_RECOVERED"

    # Mídia events
    AUDIO_GENERATED = "AUDIO_GENERATED"
    AUDIO_UPLOADED = "AUDIO_UPLOADED"
    HLS_GENERATED = "HLS_GENERATED"

    def __str__(self):
        return self.value
