from enum import Enum, unique


@unique
class Languages(Enum):
	"""Enumeration of spoken languages with common BCP 47 / ISO 639-1 language codes.

	Values are short language codes (strings) useful for TTS, translation APIs, etc.
	"""

	AFRIKAANS = "af"
	ALBANIAN = "sq"
	ARABIC = "ar"
	ARMENIAN = "hy"
	BASQUE = "eu"
	BELARUSIAN = "be"
	BENGALI = "bn"
	BOSNIAN = "bs"
	BULGARIAN = "bg"
	CATALAN = "ca"
	CHINESE_SIMPLIFIED = "zh-CN"
	CHINESE_TRADITIONAL = "zh-TW"
	CROATIAN = "hr"
	CZECH = "cs"
	DANISH = "da"
	DUTCH = "nl"
	ENGLISH = "en"
	ESPERANTO = "eo"
	ESTONIAN = "et"
	FINNISH = "fi"
	FRENCH = "fr"
	GALICIAN = "gl"
	GEORGIAN = "ka"
	GERMAN = "de"
	GREEK = "el"
	GUJARATI = "gu"
	HAITIAN_CREOLE = "ht"
	HEBREW = "he"
	HINDI = "hi"
	HUNGARIAN = "hu"
	ICELANDIC = "is"
	INDONESIAN = "id"
	IRISH = "ga"
	ITALIAN = "it"
	JAPANESE = "ja"
	KANNADA = "kn"
	KAZAKH = "kk"
	KOREAN = "ko"
	LATVIAN = "lv"
	LITHUANIAN = "lt"
	MACEDONIAN = "mk"
	MALAY = "ms"
	MALAYALAM = "ml"
	MALTESE = "mt"
	MARATHI = "mr"
	NORWEGIAN = "no"
	PERSIAN = "fa"
	POLISH = "pl"
	PORTUGUESE = "pt"
	PUNJABI = "pa"
	ROMANIAN = "ro"
	RUSSIAN = "ru"
	SERBIAN = "sr"
	SLOVAK = "sk"
	SLOVENIAN = "sl"
	SPANISH = "es"
	SWAHILI = "sw"
	SWEDISH = "sv"
	TAMIL = "ta"
	TELUGU = "te"
	THAI = "th"
	TURKISH = "tr"
	UKRAINIAN = "uk"
	URDU = "ur"
	VIETNAMESE = "vi"
	WELSH = "cy"
	XHOSA = "xh"
	ZULU = "zu"

	def __str__(self) -> str:  
		return self.value

